# Generated by Django 4.2.1 on 2023-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'student_rating',
            },
        ),
    ]
