# Generated by Django 4.2.1 on 2023-05-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerprofile_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='managerprofile',
            table='ManagerProfile',
        ),
    ]
