# Generated by Django 4.2.1 on 2023-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_managerprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrating',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
