# Generated by Django 4.2.1 on 2023-05-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentrating_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrating',
            name='username',
        ),
    ]
