# Generated by Django 4.2.1 on 2023-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentrating_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
