# Generated by Django 4.2.1 on 2023-05-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacherinfo',
            table='teacherinfo',
        ),
    ]
